apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fortune
  template:
    metadata:
      labels: 
        app: fortune
    spec:
      containers:
        - name: fortune-container
          image: octop162/fortune:1.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fortune-svc
spec:
  type: NodePort
  ports:
    - name: "http-port"
      port: 8888
      targetPort: 80
      protocol: "TCP"
  selector:
    ingress-app: fortune